 # NumPy Array Operations

#### You will create and manipulate NumPy arrays, exploring various operations, indexing, and statistical functions.


#### Task 01 : Create a NumPy Array => Initialize a NumPy array with a set of values.

In [14]:
import numpy as np

#create a numpy array

array = np.array([101,42,36,45,95,44,78,63,72])

print(f"Array : {array}")

Array : [101  42  36  45  95  44  78  63  72]


#### Task 02 : Perform Basic Operations = Execute addition, subtraction, multiplication, and division on your array.

In [15]:
addition = array + 20
substraction = array - 1
multiplication = array * 3
division = array // 2

print(f"Addition : {addition}")
print(f"Substraction : {substraction}")
print(f"Multiplication : {multiplication}")
print(f"division : {division}")

Addition : [121  62  56  65 115  64  98  83  92]
Substraction : [100  41  35  44  94  43  77  62  71]
Multiplication : [303 126 108 135 285 132 234 189 216]
division : [50 21 18 22 47 22 39 31 36]


#### Task 03 : Indexing and Slicing => Access specific elements and subsets of the array using indexing and slicing techniques.




In [22]:
array

array([101,  42,  36,  45,  95,  44,  78,  63,  72])

In [23]:
len(array)

9

In [29]:
# access single element from array
print("Element at index 4:", array[4]) 
print("Element at index 8:", array[2])

# access subset
print("Sliced Array (elements 3 to 6):", array[3:7])  
print("Sliced Array (elements 1 to 9 with 2 jumps):", array[::2])  

Element at index 4: 95
Element at index 8: 36
Sliced Array (elements 3 to 6): [45 95 44 78]
Sliced Array (elements 1 to 9 with 2 jumps): [101  36  95  78  72]


#### Task 04 : Reshaping and Transposing: => Reshape the array into different dimensions.Transpose the matrix and observe the changes.


In [54]:
array1 = np.array([[11,33,55,66,42],[5,13,51,6,4],[1,2,8,3,4]])
array1

array([[11, 33, 55, 66, 42],
       [ 5, 13, 51,  6,  4],
       [ 1,  2,  8,  3,  4]])

In [56]:
reshaped_array = array1.reshape(5, 3)
print("Reshaped Array:\n", reshaped_array)

transposed_array = reshaped_array.T
print("Transposed Array:\n", transposed_array)

Reshaped Array:
 [[11 33 55]
 [66 42  5]
 [13 51  6]
 [ 4  1  2]
 [ 8  3  4]]
Transposed Array:
 [[11 66 13  4  8]
 [33 42 51  1  3]
 [55  5  6  2  4]]


#### Task 05 : Statistical Calculations => Utilize NumPy functions to calculate: Mean, Median, Standard deviation, Variance

In [57]:
array

array([101,  42,  36,  45,  95,  44,  78,  63,  72])

In [60]:
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Mean: 64.0
Median: 63.0
Standard Deviation: 22.65686062395524
Variance: 513.3333333333334


#### Task 06 : Create Arrays with Different Data Types => Construct arrays with varying data types such as integers, floats, booleans, and strings.

In [62]:
int_array = np.array([1, 2, 3], dtype=int)
float_array = np.array([1.0, 2.5, 3.8], dtype=float)
bool_array = np.array([True, False, True], dtype=bool)
str_array = np.array(['a', 'b', 'c'], dtype=str)

print("Integer Array:", int_array)
print("Float Array:", float_array)
print("Boolean Array:", bool_array)
print("String Array:", str_array)

Integer Array: [1 2 3]
Float Array: [1.  2.5 3.8]
Boolean Array: [ True False  True]
String Array: ['a' 'b' 'c']


#### Task 07 : Concatenate Arrays => Combine multiple arrays into a single array.


In [76]:
array1

array([[11, 33, 55, 66, 42],
       [ 5, 13, 51,  6,  4],
       [ 1,  2,  8,  3,  4]])

In [77]:
array3 = np.array([[1, 3, 5, 6, 4],[ 5, 1, 8,  1,  9],[ 1,  2,  8,  3,  4]])
array3

array([[1, 3, 5, 6, 4],
       [5, 1, 8, 1, 9],
       [1, 2, 8, 3, 4]])

In [79]:
concatenated_array = np.concatenate((array1, array3))
print(f"Concatenated Array : {concatenated_array}")

Concatenated Array : [[11 33 55 66 42]
 [ 5 13 51  6  4]
 [ 1  2  8  3  4]
 [ 1  3  5  6  4]
 [ 5  1  8  1  9]
 [ 1  2  8  3  4]]


#### Task 08 : Sort Arrays => Sort your arrays in both ascending and descending order.


In [82]:
unsorted_array = np.array([58, 28, 98, 101, 65, 96, 40,10])
sorted_array_asc = np.sort(unsorted_array)
sorted_array_desc = np.sort(unsorted_array)[::-1]

print("Sorted Array (Ascending):", sorted_array_asc)
print("Sorted Array (Descending):", sorted_array_desc)

Sorted Array (Ascending): [ 10  28  40  58  65  96  98 101]
Sorted Array (Descending): [101  98  96  65  58  40  28  10]
